server:
  port: 7000

spring:
  application:
    name: api-gateway
    #开始配置网关的相关属性
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://shop-product # 增强版的uri使用服务取替代ip:port 增加了负载均衡 lb(loadBalance)
          order: 1
          #http://localhost:7000/shop-product/product/1
          #基于路由规则和过滤器 路径发生如下变化
          #http://localhost:8081/product/1
          predicates:
            - Path=/shop-product/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://shop-order
          order: 1
          predicates:
            - Path=/shop-order/**
          filters:
            - StripPrefix=1
        - id: user_route
          uri: lb://shop-user
          order: 1
          predicates:
            - Path=/shop-user/**
          filters:
            StripPrefix=1
