server:
  port: 7000

spring:
  application:
    name: api-gateway
    #开始配置网关的相关属性
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://127.0.0.1:8071 #商品服务结点 需要直接指定Ip和端口 不易维护且无法实现负载均衡
          order: 1
          #http://localhost:7000/shop-product/product/1
          #基于路由规则和过滤器 路径发生如下变化
          #http://localhost:8081/product/1
          predicates:
            - Path=/shop-product/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: http://127.0.0.1:8081
          order: 1
          predicates:
            - Path=/shop-order/**
          filters:
            - StripPrefix=1
        - id: user_route
          uri: http://127.0.0.1:8061
          order: 1
          predicates:
            - Path=/shop-user/**
          filters:
              StripPrefix=1
