server:
  port: 7000

spring:
  application:
    name: api-gateway
    #开始配置网关的相关属性
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #启用gateway路由发现 （自动取Nacos注册中心去查找服务信息）

# 声明那些请求路径不需要鉴权
auth-filter:
  excludes:
    - /shop-user/user/login
    - /shop-order/order/m1