server:
  port: 7000

spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunch_mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #开始配置网关的相关属性
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      #解决前后端分离架构跨域访问的问题
      #======================================
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      #======================================
      discovery:
        locator:
          enabled: true #启用gateway路由发现 （自动取Nacos注册中心去查找服务信息）

# 声明那些请求路径不需要鉴权
auth-filter:
  enabled: false #给过滤器加一个开关
  excludes:
    - /shop-user/user/login
    - /shop-order/order/m1