
server:
  port: 8081

spring:
  application:
    name: shop-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunch_mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  #配置nacos注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zrrd.yunchmall.pojo
  mapper-locations: classpath*:/mappers/**/*.xml
